import { upiPayUri } from "@/lib/site";

/**
 * Shows a UPI QR so visitors can scan & pay from any UPI app.
 *
 * The QR is generated server-side from the UPI id (see app/donate/page.tsx) and passed
 * in as an inline SVG — no image file or network request needed. If no QR is available
 * (e.g. UPI id not set), it degrades to a friendly placeholder instead of a broken box.
 */
export default function UpiQrCard({ upiId, qrSvg }: { upiId?: string; qrSvg?: string }) {
  const payHref = upiId ? upiPayUri(upiId) : undefined;

  return (
    <div className="card flex flex-col items-center gap-6 bg-gradient-to-br from-emerald-500/10 to-teal-500/[0.05] p-6 sm:flex-row sm:items-center sm:p-7">
      {/* QR on a white tile (QR codes need a light background) */}
      <div className="grid h-48 w-48 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white p-2.5 shadow-lg shadow-black/20">
        {qrSvg ? (
          <div
            className="h-full w-full [&>svg]:h-full [&>svg]:w-full"
            // QR markup is generated by us from the UPI id — not user input.
            dangerouslySetInnerHTML={{ __html: qrSvg }}
          />
        ) : (
          <div className="flex h-full w-full flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-300 text-center">
            <span className="text-3xl">📷</span>
            <span className="px-3 text-[11px] font-medium text-slate-500">UPI QR coming soon</span>
          </div>
        )}
      </div>

      {/* Copy */}
      <div className="text-center sm:text-left">
        <span className="chip mx-auto border-emerald-500/30 text-emerald-200 sm:mx-0">📲 UPI</span>
        <h3 className="mt-3 text-lg font-bold text-white">Scan &amp; Pay via UPI</h3>
        <p className="mt-1.5 max-w-md text-sm text-slate-300">
          Open any UPI app — Google Pay, PhonePe, Paytm or BHIM — scan the code, and chip in any amount. Every
          bit keeps Full Stack Interview Guru free and ad-light.
        </p>

        {payHref && (
          <a
            href={payHref}
            aria-label="Pay via your UPI app"
            className="btn-primary mt-4 sm:hidden"
          >
            Pay via UPI app →
          </a>
        )}
      </div>
    </div>
  );
}
