import type { Category } from "./types";

export const categories: Category[] = [
  {
    id: "core-java",
    name: "Core Java",
    icon: "☕",
    blurb: "OOP, Collections, Strings, Exceptions, JVM internals.",
    count: 150,
    topics: ["OOP", "Collections", "String", "Exceptions", "Streams", "Multithreading", "JVM"],
    accent: "from-brand-500/20 to-brand-700/10",
  },
  {
    id: "java-collections",
    name: "Java Collections",
    icon: "🗃️",
    blurb: "List/Set/Map internals, HashMap, ConcurrentHashMap, performance.",
    count: 120,
    topics: ["List vs Set vs Map", "HashMap Internals", "ConcurrentHashMap", "Iterators", "TreeMap", "Performance"],
    accent: "from-brand-400/20 to-emerald-600/10",
  },
  {
    id: "multithreading",
    name: "Multithreading",
    icon: "🧵",
    blurb: "Threads, locks, executors, the memory model, deadlocks, async.",
    count: 110,
    topics: ["Threads & Pools", "Locks", "volatile & Memory Model", "Deadlocks", "Atomics", "CompletableFuture"],
    accent: "from-brand-500/20 to-brand-700/10",
  },
  {
    id: "jvm",
    name: "JVM",
    icon: "⚙️",
    blurb: "Memory areas, garbage collection, JIT, class loading, tuning.",
    count: 90,
    topics: ["Memory Areas", "Garbage Collection", "GC Tuning", "JIT", "Class Loading", "Troubleshooting"],
    accent: "from-brand-600/20 to-ink-700/10",
  },
  {
    id: "java-8",
    name: "Java 8+",
    icon: "🚀",
    blurb: "Lambdas, Streams, Optional, functional interfaces.",
    count: 100,
    topics: ["Lambdas", "Stream API", "Optional", "Functional Interfaces", "Method References", "Default Methods"],
    accent: "from-brand-400/20 to-emerald-600/10",
  },
  {
    id: "advanced-java",
    name: "Advanced Java",
    icon: "🧬",
    blurb: "Concurrency, JVM tuning, memory model, virtual threads.",
    count: 80,
    topics: ["Concurrency", "Virtual Threads", "Memory Model", "GC Tuning", "Reflection", "Class Loading"],
    accent: "from-gold-400/20 to-brand-600/10",
  },
  {
    id: "python",
    name: "Python",
    icon: "🐍",
    blurb: "Data structures, comprehensions, decorators, the GIL.",
    count: 100,
    topics: ["Lists & Dicts", "Comprehensions", "Decorators", "Generators", "OOP", "Async"],
    accent: "from-brand-400/20 to-emerald-600/10",
  },
  {
    id: "rest-apis",
    name: "REST APIs",
    icon: "🔗",
    blurb: "HTTP verbs, status codes, idempotency, versioning.",
    count: 100,
    topics: ["HTTP Methods", "Status Codes", "Idempotency", "Auth", "Versioning", "HATEOAS"],
    accent: "from-brand-500/20 to-brand-700/10",
  },
  {
    id: "microservices",
    name: "Microservices",
    icon: "🧩",
    blurb: "Service design, communication, resilience, sagas, events, observability.",
    count: 100,
    topics: ["Service Design", "Communication", "Resilience", "Sagas & Events", "Data Consistency", "Observability"],
    accent: "from-brand-600/20 to-ink-700/10",
  },
  {
    id: "json",
    name: "JSON",
    icon: "{ }",
    blurb: "Structure, parsing, serialization, schema validation.",
    count: 50,
    topics: ["Syntax", "Parsing", "Serialization", "Schema", "JSON vs XML"],
    accent: "from-brand-600/20 to-ink-700/10",
  },
  {
    id: "sql",
    name: "SQL",
    icon: "🗄️",
    blurb: "Joins, indexes, transactions, query optimization.",
    count: 100,
    topics: ["Joins", "Indexes", "Transactions", "Normalization", "Window Functions", "Optimization"],
    accent: "from-brand-400/20 to-emerald-600/10",
  },
  {
    id: "aws",
    name: "AWS",
    icon: "☁️",
    blurb: "EC2, S3, Lambda, IAM, VPC and the well-architected pillars.",
    count: 100,
    topics: ["EC2", "S3", "Lambda", "IAM", "VPC", "DynamoDB"],
    accent: "from-brand-500/20 to-brand-700/10",
  },
  {
    id: "azure",
    name: "Azure",
    icon: "🔷",
    blurb: "App Service, Functions, Blob Storage, AKS.",
    count: 60,
    topics: ["App Service", "Functions", "Blob Storage", "AKS", "Entra ID"],
    accent: "from-brand-600/20 to-ink-700/10",
  },
  {
    id: "gcp",
    name: "GCP",
    icon: "🟦",
    blurb: "Compute Engine, Cloud Run, BigQuery, GKE.",
    count: 60,
    topics: ["Compute Engine", "Cloud Run", "BigQuery", "GKE", "Pub/Sub"],
    accent: "from-brand-400/20 to-emerald-600/10",
  },
  {
    id: "docker",
    name: "Docker",
    icon: "🐳",
    blurb: "Images, containers, layers, networking, compose.",
    count: 50,
    topics: ["Images", "Containers", "Dockerfile", "Volumes", "Networking", "Compose"],
    accent: "from-brand-500/20 to-brand-700/10",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    icon: "⎈",
    blurb: "Pods, deployments, services, scaling, self-healing.",
    count: 50,
    topics: ["Pods", "Deployments", "Services", "ConfigMaps", "Scaling", "Helm"],
    accent: "from-brand-600/20 to-ink-700/10",
  },
  {
    id: "git",
    name: "Git",
    icon: "🌿",
    blurb: "Branching, merging, rebase, resolving conflicts.",
    count: 50,
    topics: ["Branching", "Merge vs Rebase", "Stash", "Reset vs Revert", "Conflicts"],
    accent: "from-brand-400/20 to-emerald-600/10",
  },
  {
    id: "linux",
    name: "Linux",
    icon: "🐧",
    blurb: "Shell, permissions, processes, networking commands.",
    count: 50,
    topics: ["Shell", "Permissions", "Processes", "Networking", "Pipes & Redirection"],
    accent: "from-brand-600/20 to-ink-700/10",
  },
  {
    id: "ai-basics",
    name: "AI Basics",
    icon: "🤖",
    blurb: "ML vs DL, models, tokens, embeddings, inference.",
    count: 50,
    topics: ["ML vs DL", "Neural Nets", "Tokens", "Embeddings", "Training vs Inference"],
    accent: "from-gold-400/20 to-brand-600/10",
  },
  {
    id: "prompt-engineering",
    name: "Prompt Engineering",
    icon: "✨",
    blurb: "Zero/few-shot, chain-of-thought, system prompts, RAG.",
    count: 50,
    topics: ["Zero-shot", "Few-shot", "Chain of Thought", "System Prompts", "RAG"],
    accent: "from-brand-400/20 to-emerald-600/10",
  },
  {
    id: "system-design",
    name: "System Design",
    icon: "🏗️",
    blurb: "Scaling, caching, load balancing, CAP, messaging.",
    count: 100,
    topics: ["Scaling", "Caching", "Load Balancing", "CAP Theorem", "Message Queues", "Databases"],
    accent: "from-brand-500/20 to-brand-700/10",
  },
  {
    id: "behavioral",
    name: "Behavioral Questions",
    icon: "💬",
    blurb: "STAR method, conflict, leadership, ownership.",
    count: 50,
    topics: ["STAR Method", "Conflict", "Leadership", "Failure", "Teamwork"],
    accent: "from-brand-400/20 to-emerald-600/10",
  },
  {
    id: "coding-challenges",
    name: "Coding Challenges",
    icon: "⌨️",
    blurb: "Arrays, strings, hashmaps, two pointers, DP.",
    count: 200,
    topics: ["Arrays", "Strings", "HashMaps", "Two Pointers", "Recursion", "Dynamic Programming"],
    accent: "from-brand-500/20 to-brand-700/10",
  },
];

export const categoryMap = new Map(categories.map((c) => [c.id, c]));

export function getCategory(id: string): Category | undefined {
  return categoryMap.get(id);
}

export const totalQuestions = categories.reduce((sum, c) => sum + c.count, 0);
