import type { Category } from "./types";

export const categories: Category[] = [
  {
    id: "core-java",
    name: "Core Java",
    icon: "☕",
    blurb: "OOP, Collections, Strings, Exceptions, JVM internals.",
    count: 150,
    topics: ["OOP", "Collections", "String", "Exceptions", "Streams", "Multithreading", "JVM"],
    accent: "from-orange-500/20 to-amber-500/10",
  },
  {
    id: "java-8",
    name: "Java 8+",
    icon: "🚀",
    blurb: "Lambdas, Streams, Optional, functional interfaces.",
    count: 100,
    topics: ["Lambdas", "Stream API", "Optional", "Functional Interfaces", "Method References", "Default Methods"],
    accent: "from-red-500/20 to-orange-500/10",
  },
  {
    id: "advanced-java",
    name: "Advanced Java",
    icon: "🧬",
    blurb: "Concurrency, JVM tuning, memory model, virtual threads.",
    count: 80,
    topics: ["Concurrency", "Virtual Threads", "Memory Model", "GC Tuning", "Reflection", "Class Loading"],
    accent: "from-amber-600/20 to-red-600/10",
  },
  {
    id: "python",
    name: "Python",
    icon: "🐍",
    blurb: "Data structures, comprehensions, decorators, the GIL.",
    count: 100,
    topics: ["Lists & Dicts", "Comprehensions", "Decorators", "Generators", "OOP", "Async"],
    accent: "from-yellow-500/20 to-blue-500/10",
  },
  {
    id: "rest-apis",
    name: "REST APIs",
    icon: "🔗",
    blurb: "HTTP verbs, status codes, idempotency, versioning.",
    count: 100,
    topics: ["HTTP Methods", "Status Codes", "Idempotency", "Auth", "Versioning", "HATEOAS"],
    accent: "from-emerald-500/20 to-teal-500/10",
  },
  {
    id: "json",
    name: "JSON",
    icon: "{ }",
    blurb: "Structure, parsing, serialization, schema validation.",
    count: 50,
    topics: ["Syntax", "Parsing", "Serialization", "Schema", "JSON vs XML"],
    accent: "from-slate-400/20 to-slate-500/10",
  },
  {
    id: "sql",
    name: "SQL",
    icon: "🗄️",
    blurb: "Joins, indexes, transactions, query optimization.",
    count: 100,
    topics: ["Joins", "Indexes", "Transactions", "Normalization", "Window Functions", "Optimization"],
    accent: "from-sky-500/20 to-cyan-500/10",
  },
  {
    id: "aws",
    name: "AWS",
    icon: "☁️",
    blurb: "EC2, S3, Lambda, IAM, VPC and the well-architected pillars.",
    count: 100,
    topics: ["EC2", "S3", "Lambda", "IAM", "VPC", "DynamoDB"],
    accent: "from-amber-500/20 to-orange-600/10",
  },
  {
    id: "azure",
    name: "Azure",
    icon: "🔷",
    blurb: "App Service, Functions, Blob Storage, AKS.",
    count: 60,
    topics: ["App Service", "Functions", "Blob Storage", "AKS", "Entra ID"],
    accent: "from-blue-500/20 to-sky-600/10",
  },
  {
    id: "gcp",
    name: "GCP",
    icon: "🟦",
    blurb: "Compute Engine, Cloud Run, BigQuery, GKE.",
    count: 60,
    topics: ["Compute Engine", "Cloud Run", "BigQuery", "GKE", "Pub/Sub"],
    accent: "from-red-400/20 to-yellow-400/10",
  },
  {
    id: "docker",
    name: "Docker",
    icon: "🐳",
    blurb: "Images, containers, layers, networking, compose.",
    count: 50,
    topics: ["Images", "Containers", "Dockerfile", "Volumes", "Networking", "Compose"],
    accent: "from-sky-400/20 to-blue-500/10",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    icon: "⎈",
    blurb: "Pods, deployments, services, scaling, self-healing.",
    count: 50,
    topics: ["Pods", "Deployments", "Services", "ConfigMaps", "Scaling", "Helm"],
    accent: "from-blue-500/20 to-indigo-500/10",
  },
  {
    id: "git",
    name: "Git",
    icon: "🌿",
    blurb: "Branching, merging, rebase, resolving conflicts.",
    count: 50,
    topics: ["Branching", "Merge vs Rebase", "Stash", "Reset vs Revert", "Conflicts"],
    accent: "from-orange-500/20 to-red-500/10",
  },
  {
    id: "linux",
    name: "Linux",
    icon: "🐧",
    blurb: "Shell, permissions, processes, networking commands.",
    count: 50,
    topics: ["Shell", "Permissions", "Processes", "Networking", "Pipes & Redirection"],
    accent: "from-slate-400/20 to-zinc-500/10",
  },
  {
    id: "ai-basics",
    name: "AI Basics",
    icon: "🤖",
    blurb: "ML vs DL, models, tokens, embeddings, inference.",
    count: 50,
    topics: ["ML vs DL", "Neural Nets", "Tokens", "Embeddings", "Training vs Inference"],
    accent: "from-violet-500/20 to-fuchsia-500/10",
  },
  {
    id: "prompt-engineering",
    name: "Prompt Engineering",
    icon: "✨",
    blurb: "Zero/few-shot, chain-of-thought, system prompts, RAG.",
    count: 50,
    topics: ["Zero-shot", "Few-shot", "Chain of Thought", "System Prompts", "RAG"],
    accent: "from-fuchsia-500/20 to-purple-500/10",
  },
  {
    id: "system-design",
    name: "System Design",
    icon: "🏗️",
    blurb: "Scaling, caching, load balancing, CAP, messaging.",
    count: 100,
    topics: ["Scaling", "Caching", "Load Balancing", "CAP Theorem", "Message Queues", "Databases"],
    accent: "from-teal-500/20 to-emerald-600/10",
  },
  {
    id: "behavioral",
    name: "Behavioral Questions",
    icon: "💬",
    blurb: "STAR method, conflict, leadership, ownership.",
    count: 50,
    topics: ["STAR Method", "Conflict", "Leadership", "Failure", "Teamwork"],
    accent: "from-pink-500/20 to-rose-500/10",
  },
  {
    id: "coding-challenges",
    name: "Coding Challenges",
    icon: "⌨️",
    blurb: "Arrays, strings, hashmaps, two pointers, DP.",
    count: 200,
    topics: ["Arrays", "Strings", "HashMaps", "Two Pointers", "Recursion", "Dynamic Programming"],
    accent: "from-indigo-500/20 to-blue-500/10",
  },
];

export const categoryMap = new Map(categories.map((c) => [c.id, c]));

export function getCategory(id: string): Category | undefined {
  return categoryMap.get(id);
}

export const totalQuestions = categories.reduce((sum, c) => sum + c.count, 0);
